### ISSUE TITLE
Seed database with some blog posts

### ISSUE THREAD

**Issue by kfrn** [steviekaye/rails-blog#1]
It would be nice if, when you open the app, there are some existing blog posts already there to view. 
(even if you just use Lorem Ipsum text or song lyrics or whatever). 

* [Rails Guides: Migrations and Seed Data](https://guides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data)
   * You can do this via seeding or creating a migration, but I'd do the former.

You will need to run the seed command manually in Heroku after you redeploy (also, add this step to your readme setup instructions).

**Comment by steviekaye** [comment]
Added in 74f2063cd0f8a5e86d31a20627c0387c08b8deaa
