### ISSUE TITLE
Blog entry has a category

### ISSUE THREAD

**Issue by kfrn** [steviekaye/rails-blog#2]
The poster can choose from the following categories: Music, Visual Art, Film, Sports, Misc. These options should be presented in an HTML `<select>`.

For existing entries, the category should be presented on the page underneath the blog post.

It's up to you whether you backfill existing entries or not, but that would be necessary if you want the DB field to be non-nullable. (In that case, you'd probably want to do three migrations: create field, backfill, make new field non-nullable).

Can you do this in a branch and create a PR when you're ready for us to go through together :)

**Comment by steviekaye** [comment]
Added in 74f2063cd0f8a5e86d31a20627c0387c08b8deaa
